# Generated by Django 6.0.3 on 2026-03-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(help_text='Example: Python Automation Expert', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Me',
            },
        ),
    ]
