# Generated by Django 6.0.3 on 2026-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='projects/')),
                ('description', models.TextField(help_text='A brief overview of the project.')),
                ('problem_statement', models.TextField(help_text='What business problem were you solving?')),
                ('solution_details', models.TextField(help_text='How did you use Python/Django to solve it?')),
                ('result_roi', models.TextField(help_text='What was the final outcome or time saved?')),
                ('github_link', models.URLField(blank=True)),
            ],
        ),
    ]
